### ISSUE TITLE
accion realiza montones de commits innecesarios

### ISSUE THREAD

**Issue by pr0nstar** [dquintani/vacunacion#2]
La accion revisa si hubo un cambio en cualquier parte del repo antes de hacer el commit, esto siempre es verdad ya que cuando ejecutas un notebook guarda la hora de ejecucion.
![image](https://user-images.githubusercontent.com/64463227/146576535-5c98c0dd-c60b-47a3-ac7a-76fe9afcc732.png)

La idea creo es solo actualizar cuando los datos cambien, para eso seria correr 'git status ./datos' en vez de 'git status ./'.

**Comment by dquintani** [comment]
Lijto. Gracias, siempre supe que esto era problemático pero nunca me animé a preguntarles còmo arreglarlo. ヽ༼ຈل͜ຈ༽ﾉ
